# Generated by Django 3.0.8 on 2020-07-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=50)),
                ('room_amount', models.PositiveSmallIntegerField()),
                ('livers_amount', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('apartments_type', models.CharField(choices=[('Room', 'Room'), ('Number', 'Number'), ('Apartments', 'Apartments'), ('Hostel_Room', 'Hostel room')], max_length=50)),
                ('rate', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('rate', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=300)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('credit_card', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Hotel', 'Hotel'), ('Motel', 'Motel'), ('Apartments', 'Apartments'), ('Hostel', 'Hostel')], max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Apartments')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=300)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('credit_card', models.CharField(blank=True, max_length=4)),
                ('hotels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Hotel')),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('eviction_date', models.DateField()),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Apartments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image'),
        ),
    ]
